// Bundled public content. Backstage changes override these defaults in Firestore.
export const defaults = {
  home: {
    eyebrow: "SOUND / VISION / FEELING",
    heading: "SĒAN\nMOSIKILI",
    intro: "Enter the sound. Stay for the feeling.",
    image: "/assets/SEAN MOSIKILI picture.png",
    imageCaption: "SINGER / SONGWRITER / PRODUCER",
    featuredRelease: "monaco",
    announcementRelease: "lost-lovers-avenue-deluxe",
    showAnnouncement: true,
    newsletterTitle: "STAY IN THE LOOP.",
    newsletterText:
      "New music, live moments and things worth keeping. Straight from my world to your inbox.",
  },
  releases: {
    title: "THE RECORDS.",
    intro: "The singles. The projects. Every chapter.",
    items: [
      {
        id: "monaco",
        title: "MONACO",
        kind: "single",
        status: "released",
        date: "",
        image: "/assets/monaco_coverart.PNG",
        description: "Enter the sound. Stay for the feeling.",
        link: "https://unitedmasters.com/m/monaco-15",
        linkLabel: "Listen now",
        tracks: "",
        credits: "",
        order: 1,
      },
      {
        id: "lost-lovers-avenue-deluxe",
        title: "LOST LOVER'S AVENUE (Deluxe)",
        kind: "album",
        status: "upcoming",
        date: "2026-10-30",
        image: "",
        description: "Coming 30 October 2026.",
        link: "",
        linkLabel: "",
        tracks: "",
        credits: "",
        order: 2,
      },
      {
        id: "lost-lovers-avenue",
        title: "LOST LOVER'S AVENUE",
        kind: "ep",
        status: "archive",
        date: "2026-06-12",
        image: "/assets/LOSTLOVER’S AVENUE.PNG",
        description:
          "The debut EP. Seven tracks through ambition, attachment, loneliness, escapism and self-awareness.",
        link: "",
        linkLabel: "",
        tracks:
          "AMERIICAN DREAM\nWESTSIDE INTERLUDE\nGENIE\nTOO FAR GONE\nALL MINE\nSAFETY NET\nHOMEBOUND",
        credits: "",
        order: 3,
      },
      {
        id: "genie",
        title: "GENIE",
        kind: "bundle",
        status: "released",
        date: "",
        image: "/assets/GENIE_ART101.png",
        description:
          "GENIE and the Ibiza Sunset Remix. Emotional devotion meets the dance floor.",
        link: "https://unitedmasters.com/m/genie-64",
        linkLabel: "Listen now",
        tracks: "GENIE\nGENIE (Ibiza Sunset Remix)",
        credits: "Written and produced by SĒAN MOSIKILI.",
        order: 4,
      },
      {
        id: "all-mine",
        title: "ALL MINE",
        kind: "single",
        status: "archive",
        date: "",
        image: "/assets/All Mine (COver art).jpg",
        description:
          "The debut single. Late-night longing and quiet emotional pressure.",
        link: "https://music.apple.com/za/album/all-mine-single/1868987881",
        linkLabel: "Listen on Apple Music",
        tracks: "",
        credits: "Written, produced and engineered by SĒAN MOSIKILI.",
        order: 5,
      },
      {
        id: "afterhours",
        title: "ALL MINE (AFTERHOURS EDITION)",
        kind: "bundle",
        status: "archive",
        date: "",
        image: "/assets/All Mine (Afterhours edition) Cover art.jpg",
        description:
          "The expanded single, including the Loverush and Allure editions.",
        link: "https://music.apple.com/za/album/all-mine-afterhours-edition-single/1870824857",
        linkLabel: "Listen on Apple Music",
        tracks: "",
        credits: "Written, produced and engineered by SĒAN MOSIKILI.",
        order: 6,
      },
      {
        id: "fragile-exhibition",
        title: "FRAGILE EXHIBITION",
        kind: "mixtape",
        status: "archive",
        date: "",
        image: "/assets/FRAGILE EXHBITION (Mixtape by SEAN album art).png",
        description: "From the archive.",
        link: "",
        linkLabel: "",
        tracks: "",
        credits: "",
        order: 7,
      },
    ],
  },
  tour: {
    title: "SEE YOU",
    accentTitle: "LIVE.",
    intro: "Wherever you are. Meet me in the sound.",
    series: "$ONIC LAB",
    subtitle: "Live sessions.",
    description: "Two online live sessions this October.",
    poster: "/assets/TOUR POSTER.PNG",
    posterCaption: "$ONIC LAB / LIVE SESSIONS / 2026",
    ticketNote: "Visit Bandsintown for tickets and the latest show details.",
    requestUrl: "https://www.bandsintown.com/a/15631874",
    emptyText:
      "More dates are on the way. Join Swarm for the next announcement.",
    items: [
      {
        id: "sonic-lab-01",
        title: "Live session 01",
        date: "2026-10-03",
        time: "",
        timezone: "Africa/Johannesburg",
        venue: "Online",
        city: "",
        online: true,
        link: "https://www.bandsintown.com/a/15631874",
        status: "scheduled",
      },
      {
        id: "sonic-lab-02",
        title: "Live session 02",
        date: "2026-10-10",
        time: "",
        timezone: "Africa/Johannesburg",
        venue: "Online",
        city: "",
        online: true,
        link: "https://www.bandsintown.com/a/15631874",
        status: "scheduled",
      },
    ],
  },
  visuals: {
    title: "IN FRAME.",
    intro: "The moving image. The moments between.",
    items: [
      {
        id: "all-mine-video",
        title: "ALL MINE",
        kind: "Lyric video",
        description: "The official lyric video.",
        url: "https://www.youtube.com/watch?v=Pyn5b6m_Fac",
        image: "",
        status: "published",
        order: 1,
      },
      {
        id: "all-mine-teaser",
        title: "ALL MINE (OFFICIAL TEASER)",
        kind: "Teaser",
        description: "The Afterhours edition.",
        url: "https://www.youtube.com/watch?v=1XS_H6hsP30",
        image: "",
        status: "published",
        order: 2,
      },
    ],
  },
  shop: {
    title: "[SEANWXRLD]",
    intro: "A piece of the world.\nSomething to make your own.",
    serviceTitle: "FOUND YOUR PIECE?",
    serviceText:
      "Choose an item and send a request. We’ll follow up on availability and shipping before payment or delivery is arranged.",
  },
  pages: {
    aboutTitle: "The Art of SĒAN MOSIKILI",
    aboutBody:
      "SĒAN MOSIKILI (Tswelopele Sean Mosikili, born April 11, 2005) is a South African singer, songwriter, and record producer creating music that blends contemporary pop, dark pop, alternative R&B, and cinematic sound design. His work is known for its emotional precision, layered vocal production, and atmospheric textures that combine pop accessibility with deeper storytelling.\n\nMosikili was born in Vanderbijlpark, South Africa, to Johannes Mosikili and Emily Mosikili, and grew up in a creatively supportive suburban household where artistic exploration was actively encouraged. From an early age, he displayed a quiet but curious personality, often described as observant, creative, and eager to explore new ideas. His parents fostered an environment where imagination and ambition were not limited, encouraging their children to think beyond conventional boundaries and pursue their passions with confidence.\n\nMusic was constantly present in the Mosikili household. His mother, Emily Mosikili, was a praise and worship singer who had considered pursuing professional music before starting her family. She performed regularly in church settings and even sang at a stadium event for a pastor she frequently collaborated with. Both of his parents participated in choir and shared a love for singing together at home. His father, Johannes Mosikili, is also a pianist, and their home frequently centered around music, whether through singing, playing instruments, or informal family performances.\n\nGrowing up in this environment naturally shaped Mosikili’s relationship with music. As a child he began writing songs in primary school, often keeping a small personal “songbook” where he experimented with lyrics and melodies. One unexpected influence came from the animated television series Grojband, which inspired him to begin writing original songs rather than simply singing along to existing music. Around this time he would organize informal performances with cousins in the backyard, repurposing existing instrumentals, writing new lyrics, creating choreography, and even designing visual ideas for performances staged for family members.\n\nMosikili and his siblings were also encouraged to pursue their artistic interests formally. His brother Saint Mosikili received his first guitar in sixth grade and later studied music in high school as well. While Saint’s interests eventually leaned more toward visual arts, storytelling, and digital content creation, the two continue to collaborate creatively, with Saint contributing visually while Mosikili often manages aspects of his brother’s influencer career. The siblings remain creative partners, particularly in music production.\n\nMosikili attended Vaalpark Articon, a performing arts-focused secondary school that requires auditions for admission and has produced numerous artists across music, dance, and visual arts. During his time there he studied music academically from Grade 8 through Grade 12, completing formal training through the UNISA and Trinity College London music programs. His studies included music theory, sight-singing, music history, piano performance, and technical musicianship.\n\nIn his final year of secondary school he completed Grade 5 in music performance and earned Half South African Colours recognition through the Con Spirito Music Festival, reflecting his dedication to formal musical training.\n\nAlthough songwriting had always been central to his identity, Mosikili spent years developing his vocal abilities through both formal training and independent study. Early recordings reveal a developing voice that he later refined through extensive practice, including online vocal coaching resources such as Cheryl Porter’s training programs alongside his school-based vocal instruction. Through years of disciplined practice, he gradually developed the controlled falsetto and layered vocal style that characterizes his current recordings.\n\nBefore learning music production, Mosikili frequently recorded melody ideas using voice memos, later transforming them into full compositions on piano or through digital production. His piano training began more seriously around 2019 and became a foundational part of his songwriting process.\n\nMosikili began exploring music production in 2018 using FL Studio. Initially struggling with the technical aspects of digital audio production, he spent years learning through experimentation, tutorials, and repeated trial and error. His first fully realized instrumental production emerged in 2022, marking a turning point in his creative independence as both a songwriter and producer. From that point onward his production style developed rapidly, allowing him to shape complete sonic worlds around his lyrics and vocal ideas.\n\nHis musical style merges contemporary pop songwriting structures with darker tonal palettes often associated with alternative R&B and cinematic electronic production. Mosikili describes his goal as creating music that feels emotionally immersive while remaining melodically engaging — a balance between introspective storytelling and accessible pop composition. His sonic inspirations include artists such as Nicki Minaj, whose career encouraged him to pursue music seriously, as well as The Weeknd, RAYE, Chlöe Bailey, and occasionally the atmospheric production styles associated with Travis Scott.\n\nCinematic visual storytelling also plays a central role in his artistic vision. He frequently references the mood and atmosphere of films produced by A24 — including works such as Moonlight and Waves — as influences on the emotional tone and visual aesthetic he seeks to translate into music.\n\nIn addition to music, Mosikili has a strong interest in fashion design. In 2024 he began formally studying fashion while also co-founding the luxury footwear brand La Ínfinitè with his mother Emily Mosikili. The brand specializes in custom-designed Italian footwear manufactured in the La Marche region of Italy and focuses on classic high-end pumps combining elegance, craftsmanship, and distinctive design concepts. The company operates within the Italian luxury shoe marketplace and reflects Mosikili’s interest in merging fashion with artistic identity.\n\nHis debut single, ALL MINE, was released on January 23, 2026. The contemporary dark pop track features a tempo of 127 BPM and incorporates layered falsetto vocals, rhythmic vocal chops, restrained electronic instrumentation, and a glitch-styled outro. The song explores themes of emotional fixation, desire, and self-deception within an imbalanced romantic relationship, positioning Mosikili within the evolving alt-pop landscape.\n\nThe single serves as the introduction to his official release catalog, which has since expanded into a broader campaign that now includes FRAGILE EXHIBITION, a mixtape scheduled for early April 2026. The project is being introduced with a cleaner rollout structure across the site, including dedicated visuals, updated release notes, and an emphasis on emotional storytelling through dark pop, alternative R&B, and minimalist production.\n\nAn expanded version of the debut single, ALL MINE (AFTERHOURS EDITION), was released on January 28, 2026. The deluxe bundle features additional versions of the track, including the “Loverush Edition” and the “Allure Edition,” designed to reinterpret the song’s emotional atmosphere across different listening contexts.\n\nThe current rollout also includes I DON'T CARE! as the lead single for FRAGILE EXHIBITION, while DOPAMINE HIGH is now scheduled to drop on April 10, 2026. Across the site, all release references have been updated to keep the visual and editorial presentation aligned with that new sequence.\n\nFor Mosikili, music functions as both emotional expression and psychological release. He describes songwriting and production as a process that allows both artist and listener to navigate complex emotions, transforming personal experiences into shared emotional understanding.",
    contactTitle: "LET’S TALK.",
    contactIntro: "Bookings, licensing, collaborations. Start a conversation.",
    contactNote:
      "Include dates, deliverables, budget range, usage intent, and any press deadlines.",
    swarmTitle: "A LITTLE CLOSER.",
    swarmIntro:
      "For you. The fans. New music, early links and live updates from SĒAN MOSIKILI.",
    swarmBenefits:
      "Priority access to music links, event announcements, limited merch and private teasers.",
  },
  settings: {
    artistName: "SĒAN MOSIKILI",
    description:
      "SĒAN MOSIKILI is a South African singer, songwriter and producer. Pop, contemporary R&B and electronic dance-pop.",
    artistImage: "/assets/SEAN MOSIKILI picture.png",
    genres: "Pop, Electronic Dance Pop, Alternative R&B, Alternative Pop",
    location: "Johannesburg, South Africa",
    socials: [
      {
        label: "Instagram",
        url: "https://www.instagram.com/seanwxrld",
      },
      {
        label: "YouTube",
        url: "https://www.youtube.com/@seanwxrld",
      },
      {
        label: "X",
        url: "https://x.com/seanwxrld",
      },
      {
        label: "TikTok",
        url: "https://www.tiktok.com/@seanwxrld",
      },
      {
        label: "Apple Music",
        url: "https://music.apple.com/us/artist/s%C4%93an-mosikili/1868976258",
      },
      {
        label: "Spotify",
        url: "https://open.spotify.com/artist/5yU7mw9J7mmv5ubNcA1O1P",
      },
      {
        label: "Tidal",
        url: "https://tidal.com/artist/73061343",
      },
      {
        label: "Deezer",
        url: "https://www.deezer.com/artist/367447902",
      },
      {
        label: "Amazon Music",
        url: "https://music.amazon.com/artists/B0GGSBZGNC/s%C4%93an-mosikili",
      },
    ],
  },
};
